# Use the official Apache Airflow image as the base image
FROM apache/airflow:2.10.2

# Install necessary system dependencies for Camelot and other libraries
USER root
RUN apt-get update \
    && apt-get install -y \
    ntpdate \
    build-essential \
    python3-dev \
    python3-pip \
    libxml2-dev \
    libxslt-dev \
    libz-dev \
    libjpeg-dev \
    libssl-dev \
    poppler-utils \
    ghostscript \
    tesseract-ocr \
    libgomp1 \
    && apt-get clean

# Sync time to prevent AWS S3 time mismatch errors
RUN ntpdate pool.ntp.org

# Switch back to airflow user
USER airflow

# Set the correct environment variables to include user-installed packages
ENV PATH="/home/airflow/.local/bin:${PATH}"

# Install Python libraries using pip
RUN pip install --user --no-cache-dir pandas streamlit numpy pypdf2 pdfplumber \
    boto3 pdfminer.six camelot-py[cv] tiktoken chatgpt_operator

# Expose the default Airflow port
EXPOSE 8080

# Copy over the DAGs and configuration (if needed)
COPY ./dags /opt/airflow/dags
COPY ./plugins /opt/airflow/plugins

# Set the entrypoint for Airflow
ENTRYPOINT ["entrypoint.sh"]

# Run the Airflow webserver as the default service
CMD ["webserver"]